name: "Test"
on:
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: ./ci/test.sh
